In [2]:
#166. Importing numpy to process arrays.
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#167. NumPy as np
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
#168. Checking NumPy Version
import numpy as np

print(np.__version__)

1.18.5


In [5]:
#169. The array object in NumPy is called ndarray.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#170. Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [7]:
#171. 0-D arrays
import numpy as np
arr=np.array(22)
print (arr)

22


In [8]:
#172. 1-D arrays
import numpy as np
arr=np.array([1,2,3])
print (arr)

[1 2 3]


In [9]:
#173. 2-D Arrays
import numpy as np
arr=np. array([[1,2,3],[9,8,7]])
print (arr)

[[1 2 3]
 [9 8 7]]


In [10]:
#174. 3-D arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
